In [365]:
from sklearn import linear_model
import numpy as np
from sklearn.model_selection import train_test_split
import pandas as pd

In [366]:
df = pd.read_csv("diabetes.csv")

In [367]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [368]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [369]:
x = df.drop("Outcome", axis=1)

In [370]:
y = df["Outcome"]

In [371]:
y.shape

(768,)

In [372]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [373]:
X_test

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
712,10,129,62,36,0,41.2,0.441,38
422,0,102,64,46,78,40.6,0.496,21
248,9,124,70,33,402,35.4,0.282,34
201,1,138,82,0,0,40.1,0.236,28
398,3,82,70,0,0,21.1,0.389,25
...,...,...,...,...,...,...,...,...
415,3,173,84,33,474,35.7,0.258,22
17,7,107,74,0,0,29.6,0.254,31
511,0,139,62,17,210,22.1,0.207,21
753,0,181,88,44,510,43.3,0.222,26
469,6,154,78,41,140,46.1,0.571,27

In [374]:
model= linear_model.LinearRegression()

In [375]:
model.fit(X_train,y_train)

LinearRegression()

In [376]:
X_test.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
712,10,129,62,36,0,41.2,0.441,38
422,0,102,64,46,78,40.6,0.496,21
248,9,124,70,33,402,35.4,0.282,34
201,1,138,82,0,0,40.1,0.236,28
398,3,82,70,0,0,21.1,0.389,25

In [377]:
out1 = model.predict(X_test)

In [392]:
out1

array([ 0.69367488,  0.27371274,  0.44357825,  0.45638439, -0.03967095,
        0.23294396,  0.42505042,  0.59706307,  0.68693111,  0.38538474,
        0.18654408, -0.03596834,  0.36122827,  0.60238952,  0.01797658,
        0.27210842,  0.59601384,  0.28199076,  0.91803087,  0.87251603,
        0.35360282,  0.619976  ,  0.43393259,  0.38842959,  0.66123602,
        0.09089967,  0.15736562,  0.34894547,  0.15865568,  0.57928571,
        0.2438648 ,  0.32272993,  0.09836537,  0.42852872,  0.4548728 ,
        0.64431599,  0.4492437 , -0.00140927,  0.49408818,  0.09258253,
        0.34176863,  0.41978539,  0.69281516,  0.13302168,  0.71758618,
        0.21856822,  0.49898009, -0.27752673,  0.05564301,  0.49288141,
        0.33679545,  0.33344249, -0.04316242,  0.34481206,  0.7483217 ,
        0.84814663,  0.37968585,  0.2929145 ,  0.45736013,  0.31475271,
        0.24025928,  0.10833785,  0.32327387,  0.56907214,  0.65434994,
        0.61460437,  0.21136854,  0.61952582,  0.66930501,  0.85386571,
        0.12684432,  0.35047281,  0.34675717,  0.78564857, -0.12362686,
        0.400842  ,  0.33984068,  0.68169257,  0.35038842,  0.23776234,
        0.14529249,  0.17056571, -0.03524306,  0.23978737,  0.6534578 ,
        0.20252203,  0.74410946,  0.34354948,  0.73853166,  0.26668645,
        0.20695205,  0.49635493,  0.41067912, -0.08690587,  0.14702308,
        0.19196922,  0.04776141,  0.56049069,  0.36549484,  0.09029358,
        0.21315028,  0.15703243,  0.5717511 ,  0.32180213,  0.52460054,
        0.21709325,  0.72268233,  0.29742783,  0.03921729,  0.97902125,
        0.22769123,  0.00152071,  0.63269439,  0.27310459,  0.32238707,
        0.36340369,  0.30030015,  1.11416001,  0.66707226,  0.11550319,
        0.50683124,  0.70507792,  0.33807681, -0.02648025,  0.21550342,
        0.23294716,  0.40837742,  0.24616099,  0.83946791,  0.5766099 ,
        1.0178425 ,  0.3726282 ,  0.42399771,  0.3821945 ,  0.52684959,
        0.15314488,  0.19907779,  0.24661117,  0.02861474,  0.25540823,
        0.36314578,  0.60872445,  0.42639589,  0.15302506,  0.5699473 ,
        0.19562783,  0.34236885,  0.64200818,  0.29073057,  0.52450601,
        0.28840691,  0.17321296,  0.59168232,  0.75397863])

In [379]:
y_test

712    1
422    0
248    0
201    0
398    0
      ..
415    1
17     1
511    0
753    1
469    0
Name: Outcome, Length: 154, dtype: int64

In [380]:
er=y_test - out1

In [381]:
er.head(50)

712    0.306325
422   -0.273713
248   -0.443578
201   -0.456384
398    0.039671
373   -0.232944
628   -0.425050
44    -0.597063
425    0.313069
198    0.614615
416   -0.186544
607    0.035968
652   -0.361228
699   -0.602390
589   -0.017977
475   -0.272108
221    0.403986
389   -0.281991
761    0.081969
715    0.127484
613   -0.353603
495   -0.619976
301    0.566067
351   -0.388430
702    0.338764
463   -0.090900
465   -0.157366
747   -0.348945
654   -0.158656
231    0.420714
519   -0.243865
73    -0.322730
491   -0.098365
356    0.571471
285   -0.454873
673   -0.644316
453   -0.449244
239    0.001409
642    0.505912
600   -0.092583
727   -0.341769
233   -0.419785
647    0.307185
208   -0.133022
681    0.282414
659    0.781432
580    0.501020
81     0.277527
720   -0.055643
246   -0.492881
Name: Outcome, dtype: float64

In [387]:
mmdtest = np.array([[0,80,40,35,90,30,0.2,18]])
mmd = model.predict(mmdtest)

C:\Users\ASUS\AppData\Roaming\Python\Python38\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [394]:
if mmd > 0.5:  
    print(1)  
elif mmd < 0.5:  
    print(0)  
else:  
    print("out1 is equal to 0.5")

0